### ISSUE TITLE
Issue1

### ISSUE THREAD

**Issue by paripukazhenthi** [DoctrinaManagement/Doctrina#1]
Quiz list not show to students @Basheer-Ahamed   [see](https://docs.zoho.com/file/4rd8ddbbe5e70780f4b4da2948b7c371c5cd7)

**Comment by DoctrinaManagement** [comment]
It is fixed. It's also the same problem. You using an secure network so Websocket makes an error and  all pages has throw an error. please check it now with normal network ..
