### ISSUE TITLE
Comment , Post Issue

### ISSUE THREAD

**Issue by paripukazhenthi** [DoctrinaManagement/Doctrina#11]
Sometimes in the feeds, comment and post do not work  @pandeshwaran .  [See this](https://docs.zoho.com/file/4rd8d997bde949a8c488d9613e0330e602482)

**Comment by DoctrinaManagement** [comment]
Actually it's not a Error. It's a Regex checking. We provide minimum 3 characters to post & comment & reply So it's not working. I will reduce the length 3 to 1 ...
