### ISSUE TITLE
Rating Issue

### ISSUE THREAD

**Issue by paripukazhenthi** [DoctrinaManagement/Doctrina#9]
The rating field doesn't allows short value.
[See This](https://docs.zoho.com/file/4rd8de86e84bf1ad2440c8770a896833069fd)

**Comment by DoctrinaManagement** [comment]
It is also a regex checking problem.it's now fixed.

**Comment by DoctrinaManagement** [comment]
Description should have minimum 5 characters so it's throw an error.we fixed now to minimum 4 characters
